// Manually kept in sync with button_codes.h in the firmware.
export enum ButtonCode {
    POWER      = "POWER",
    SOURCE     = "SOURCE",
    DPAD_UP    = "DPAD_UP",
    DPAD_DOWN  = "DPAD_DOWN",
    DPAD_LEFT  = "DPAD_LEFT",
    DPAD_RIGHT = "DPAD_RIGHT",
    DPAD_CENTER = "DPAD_CENTER",
    BACK       = "BACK",
    HOME       = "HOME",
    PLAY_PAUSE = "PLAY_PAUSE",
    MUTE       = "MUTE",
    VOL_UP     = "VOL_UP",
    VOL_DOWN   = "VOL_DOWN",
    PAGE_UP    = "PAGE_UP",
    PAGE_DOWN  = "PAGE_DOWN",
    PROG_1     = "PROG_1",
    PROG_2     = "PROG_2",
    PROG_3     = "PROG_3",
    PROG_4     = "PROG_4",
    PROG_5     = "PROG_5",
    PROG_6     = "PROG_6",
}
